// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjd6wjCHMPtxqb-bIhXy0OG7V0kKo0u5c',
    appId: '1:111247537996:web:5f8c6394fa83b7538341e9',
    messagingSenderId: '111247537996',
    projectId: 'irecycle-gp',
    authDomain: 'irecycle-gp.firebaseapp.com',
    storageBucket: 'irecycle-gp.appspot.com',
    measurementId: 'G-P0L3K8FQLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcfoJjKPEFSzb-gSIN2NPCvT8WtCdiUyk',
    appId: '1:111247537996:android:b19d69fb1ead5fab8341e9',
    messagingSenderId: '111247537996',
    projectId: 'irecycle-gp',
    storageBucket: 'irecycle-gp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF-uqoRBmrZyjYHSb7N0ODycmYPKhNbt0',
    appId: '1:111247537996:ios:6f61f70d04d3e5f78341e9',
    messagingSenderId: '111247537996',
    projectId: 'irecycle-gp',
    storageBucket: 'irecycle-gp.appspot.com',
    iosClientId: '111247537996-d4jqa553vbhtrpflk3avhb9ph9obqe2j.apps.googleusercontent.com',
    iosBundleId: 'com.example.irecycle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF-uqoRBmrZyjYHSb7N0ODycmYPKhNbt0',
    appId: '1:111247537996:ios:6f61f70d04d3e5f78341e9',
    messagingSenderId: '111247537996',
    projectId: 'irecycle-gp',
    storageBucket: 'irecycle-gp.appspot.com',
    iosClientId: '111247537996-d4jqa553vbhtrpflk3avhb9ph9obqe2j.apps.googleusercontent.com',
    iosBundleId: 'com.example.irecycle',
  );
}
